// src/constants/errorCodes.ts
export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_JSON: "INVALID_JSON",

  // Database (Prisma)
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  NOT_FOUND: "NOT_FOUND",
  INVALID_RELATION: "INVALID_RELATION",
  RELATION_VIOLATION: "RELATION_VIOLATION",
  DATABASE_ERROR: "DATABASE_ERROR",
  DATABASE_VALIDATION_ERROR: "DATABASE_VALIDATION_ERROR",

  // Generic
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];