// src/constants/errorCodes.ts
export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // OTP / Email verification
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_MAX_ATTEMPTS: "OTP_MAX_ATTEMPTS",
  OTP_RESEND_TOO_SOON: "OTP_RESEND_TOO_SOON",
  OTP_RATE_LIMITED: "OTP_RATE_LIMITED",
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  OTP_EMAIL_SEND_FAILED: "OTP_EMAIL_SEND_FAILED",
  VERIFICATION_REQUIRED: "VERIFICATION_REQUIRED",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_JSON: "INVALID_JSON",

  // Database (Prisma)
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  NOT_FOUND: "NOT_FOUND",
  INVALID_RELATION: "INVALID_RELATION",
  RELATION_VIOLATION: "RELATION_VIOLATION",
  DATABASE_ERROR: "DATABASE_ERROR",
  DATABASE_VALIDATION_ERROR: "DATABASE_VALIDATION_ERROR",

  // Booking
  BOOKING_DATE_OVERLAP: "BOOKING_DATE_OVERLAP",
  BOOKING_INVALID_DATE_RANGE: "BOOKING_INVALID_DATE_RANGE",
  BOOKING_PENDING_LIMIT_EXCEEDED: "BOOKING_PENDING_LIMIT_EXCEEDED",
  BOOKING_GUEST_CAPACITY_EXCEEDED: "BOOKING_GUEST_CAPACITY_EXCEEDED",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_ALREADY_PROCESSED: "BOOKING_ALREADY_PROCESSED",
  BOOKING_EXPIRED: "BOOKING_EXPIRED",
  BOOKING_FORBIDDEN: "BOOKING_FORBIDDEN",
  BOOKING_INVALID_STATUS_TRANSITION: "BOOKING_INVALID_STATUS_TRANSITION",
  BOOKING_CANNOT_CANCEL: "BOOKING_CANNOT_CANCEL",

  // Generic
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
